// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDe-zh-h_b62_SfKUCv1WVGn6fuXEa9h4',
    appId: '1:724163833439:web:bd8e075fb8f52625c935ea',
    messagingSenderId: '724163833439',
    projectId: 'ra7ti-cd141',
    authDomain: 'ra7ti-cd141.firebaseapp.com',
    storageBucket: 'ra7ti-cd141.firebasestorage.app',
    measurementId: 'G-TLKTTHMMYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCES8AR4-OlzhwVpBXSm-nMw-WYbq0I2ZA',
    appId: '1:724163833439:android:45aabaab35e05556c935ea',
    messagingSenderId: '724163833439',
    projectId: 'ra7ti-cd141',
    storageBucket: 'ra7ti-cd141.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSVBMhQkhZg79nHk6vs2JWUwNlfQ1VGRk',
    appId: '1:724163833439:ios:2a148e9845536ae7c935ea',
    messagingSenderId: '724163833439',
    projectId: 'ra7ti-cd141',
    storageBucket: 'ra7ti-cd141.firebasestorage.app',
    iosBundleId: 'com.rahty.fasslagroups',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSVBMhQkhZg79nHk6vs2JWUwNlfQ1VGRk',
    appId: '1:724163833439:ios:4828edc2ef324288c935ea',
    messagingSenderId: '724163833439',
    projectId: 'ra7ti-cd141',
    storageBucket: 'ra7ti-cd141.firebasestorage.app',
    iosBundleId: 'com.sixamtech.ridesharinguser.rideSharingUserApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDe-zh-h_b62_SfKUCv1WVGn6fuXEa9h4',
    appId: '1:724163833439:web:552624fbb9d082d3c935ea',
    messagingSenderId: '724163833439',
    projectId: 'ra7ti-cd141',
    authDomain: 'ra7ti-cd141.firebaseapp.com',
    storageBucket: 'ra7ti-cd141.firebasestorage.app',
    measurementId: 'G-SPQ309XDCG',
  );

}